routes:
  /:
    data: page.home
    template: index
  /locations/: locations
  /calendar/: calendar

collections:
  /:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/