routes:
  /:
    data: page.home
    template: index
  /locations/: locations
  /calendar/: calendar
  /community/: community
  /activity/: activity

collections:
  /:
    permalink: /hot/{slug}/
    template: index
    filter: primary_tag:index
  /news/:
    permalink: /news/{slug}/
    template: news

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/