routes:
  /:
    data: page.home
    template: index
  /locations/: locations
  /calendar/: calendar
  /community/: community
  /activity/: activity

  /activity/index.html/: activity-index.hbs

  /community/1-1/: community1-1
  /community/1-2/: community1-2
  /community/1-3/: community1-3

  /community/2-1/: community2-1
  /community/2-2/: community2-2
  /community/2-3/: community2-3

  /community/3-1/: community3-1
  /community/3-2/: community3-2
  /community/3-3/: community3-3

collections:
  /:
    permalink: /hot/{slug}/
    template: index
    filter: primary_tag:index
  /news/:
    permalink: /news/{slug}/
    template: news

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/