name: Deploy Theme
on:
  push: 
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm run zip
      - name: Deploy Ghost Theme
        env:
          API_URL: ${{ secrets.GHOST_ADMIN_API_URL }}
          API_KEY: ${{ secrets.GHOST_ADMIN_API_KEY }}
        run: ./upload-theme.sh
