name: Deploy Theme
on:
  push: 
    branches:
      - dev
      - master
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm run build          
      - name: Deploy Ghost Theme
        uses: TryGhost/action-deploy-theme@master
        with:
          api-url: ${{ secrets.GHOST_ADMIN_API_URL }}
          api-key: ${{ secrets.GHOST_ADMIN_API_KEY }}
          theme-name: custom
          exclude: '*node_modules/*'
